extends Control

@onready var OkGoButton = $OkGoButton
var target_scene = "res://scenes/online_lobbies.tscn"
# Called when the node enters the scene tree for the first time.

# Prevents the button from being pressed multiple times while transitioning.
var used := false

@onready var Username: LineEdit = $UsernameEditField/LineEdit

func _ready() -> void:
	OkGoButton.pressed.connect(_on_player_ready)
	visible = false
	
	_update_username()
	_random_placeholder()
	


func _process(delta: float) -> void:
	_update_username()

func _on_player_ready():
	visible = false
	
	# Extract skin IDs safely.
	var ship_id: int = PlayerConfig.get_ship_skin_id()
	var pilot_id: int = PlayerConfig.get_pilot_skin_id()
	
	print("Joining server with ship skin: ", ship_id, " and pilot skin: ", pilot_id)
	
	# Creates the press animation immediately.
	var tween := create_tween()
	tween.tween_property(self, "scale", Vector2(0.85, 0.85), 0.12)
	tween.tween_property(self, "scale", Vector2.ONE, 0.15)
	
	# ==================================================
	# API CALL
	# ==================================================
	
	var response_data: Dictionary = await Api.join_server(PlayerConfig.username, ship_id, pilot_id)

	# Wait until the visual animation finishes before reacting.
	if tween.is_running():
		await tween.finished

	# ==================================================
	# SERVER RESPONSE HANDLING
	# ==================================================
	
	# Check if the server responded with valid data.
	if not response_data.is_empty() and response_data.has("id"):
		print("Player successfully joined the server!")
		
		
		# Assign the unique ID generated by the server to the local config.
		PlayerConfig.online_id = int(response_data["id"])
		print("Assigned Player ID: ", PlayerConfig.online_id)
		PlayerConfig.in_lobby = true
		get_tree().change_scene_to_file(target_scene)
		
		
			
	else:
		# If an error occurs, allow the user to try again.
		used = false
		push_error("JoinServerButton: Failed to execute join server sequence.")
	
	if used:
		return
		
	used = true

	
	
func _update_username() -> void:
	if Username.text == "":
		PlayerConfig.username = Username.placeholder_text
	else:
		PlayerConfig.username = Username.text
		


func _random_placeholder():
	var random_name = names.pick_random()	
	Username.placeholder_text = random_name

var names: Array[String] = [
	"Sapo",
	"Ave",
	"Fogo",
	"Vapo",
	"Simus",
	"Lumi",
	"Nino",
	"Kiko",
	"Lulu",
	"Mimi",
	"Pipo",
	"Tico",
	"Tutu",
	"Bibi",
	"Zuzu",
	"Fifi",
	"Juju",
	"Yumi",
	"Kuma",
	"Neko",
	"Momo",
	"Puki",
	"Yuki",
	"Ruru",
	"Lilo",
	"Tobi",
	"Zico",
	"Balu",
	"Fofa",
	"Amora",
	"Mel",
	"Lua",
	"Sol",
	"Neo",
	"Zeno",
	"Filo",
	"Fuzu",
	"Pika",
	"Riko",
	"Miko",
	"Kiki",
	"Zaza",
	"Coco",
	"Nana",
	"Vivi",
	"Lupi",
	"Foxy",
	"Chibi",
	"Mini",
	"Pixel"
]
	
	
