extends TextureButton

# The scene that will be loaded after this button animation and network request finish.
@export_file("*.tscn") var target_scene: String

# Prevents the button from being pressed multiple times while transitioning.
var used := false

# ==================================================
# INITIALIZATION
# ==================================================

func _ready() -> void:
	# Creates a pixel-perfect click area based on the button texture transparency.
	create_click_mask()

	# Makes the scale animation happen from the center of the button.
	pivot_offset = size / 2.0

	# Connects the button press event.
	pressed.connect(_on_pressed)


# ==================================================
# CLICK MASK
# ==================================================

func create_click_mask() -> void:
	# Only create the mask if the button has a normal texture assigned.
	if texture_normal:
		var bitmap := BitMap.new()

		# Uses the texture alpha values:
		# - Visible pixels become clickable
		# - Transparent pixels become ignored
		bitmap.create_from_image_alpha(texture_normal.get_image())

		# Applies the generated pixel-perfect click mask to the button.
		texture_click_mask = bitmap


# ==================================================
# BUTTON PRESS & NETWORK REQUEST
# ==================================================

func _on_pressed() -> void:
	# Ignore additional clicks if the button was already activated.
	if used:
		return
		
	used = true

	# Play click sound.
	AudioManager.play_ui_sound("button")
	
	# Extract skin IDs safely.
	var ship_id: int = PlayerConfig.ship_skin.get("id", 0)
	var pilot_id: int = PlayerConfig.pilot_skin.get("id", 0)
	
	print("Joining server with ship skin: ", ship_id, " and pilot skin: ", pilot_id)
	
	# Creates the press animation immediately.
	var tween := create_tween()
	tween.tween_property(self, "scale", Vector2(0.85, 0.85), 0.12)
	tween.tween_property(self, "scale", Vector2.ONE, 0.15)
	
	# ==================================================
	# API CALL
	# ==================================================
	
	var response_data: Dictionary = await Api.join_server(PlayerConfig.username, ship_id, pilot_id)

	# Wait until the visual animation finishes before reacting.
	if tween.is_running():
		await tween.finished

	# ==================================================
	# SERVER RESPONSE HANDLING
	# ==================================================
	
	# Check if the server responded with valid data.
	if not response_data.is_empty() and response_data.has("id"):
		print("Player successfully joined the server!")
		
		# Assign the unique ID generated by the server to the local config.
		PlayerConfig.online_id = int(response_data["id"])
		print("Assigned Player ID: ", PlayerConfig.online_id)
		
		# Change scene ONLY if the request was successful.
		if not target_scene.is_empty():
			get_tree().change_scene_to_file(target_scene)
		else:
			push_error("JoinServerButton: Target scene is not assigned.")
			
	else:
		# If an error occurs, allow the user to try again.
		used = false
		push_error("JoinServerButton: Failed to execute join server sequence.")
